#!/bin/bash
CURR_BRANCH=$(git branch | grep \* | cut -d ' ' -f2)
CURR_DEST=$( git config  --get branch.${CURR_BRANCH}.gerrit)
CURR_DEST_BRANCH=$(basename ${CURR_DEST})

cat<<EOF

==============================================
Your Topic branch name is ${CURR_BRANCH}

Your Destination branch in Gerrit is ${CURR_DEST_BRANCH}

==============================================

EOF

git fetch 

echo 
echo "YOUR NEW COMMITS..."
echo 

git log origin/${CURR_DEST_BRANCH}..HEAD

echo 
echo "MISSING COMMITS ...git syncup needed"
echo 

git log HEAD..origin/${CURR_DEST_BRANCH}

